### ISSUE TITLE
Are these slang terms?

### ISSUE THREAD

**Issue by cosmicblend** [reiver/fediverse-archetypes#1]
I've never heard the following terms before. Are they established slangs or titles your assigning to an observed group?

- fingerer
- gopherer
- tildeversalist
- twtxter
- uxner

**Comment by reiver** [comment]
I made them up using English language rules.

You can add the -er suffix to the end of a noun to describe a person is associated with, or does, etc that thing.

For example —

* "baby boom" -> "baby boomer"

...

If you have alternative suggestions, I am open to considering them.

**Comment by reiver** [comment]
OK, I'm going to close this (since there doesn't seem to be anymore discussion).
